name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  # Nothing!

  ### Usually a bad idea / not recommended
  token:
    description: Specify token (GH or PAT), instead of inheriting one from the calling workflow
    default: ${{ github.token }}

outputs:
  pr:
    description: 'Associated pull request number'
    value: ${{ steps.vars.outputs.pr }}

runs:
  using: composite
  steps:
    # Process variables and inputs
    - uses: actions/checkout@v4
    - id: vars
      shell: bash
      run: |
        set -eux
        
        # Get PR number (different process for merge queue)
        if [ ${{ github.event_name }} == 'pull_request' ]
        then
          echo "Event type: pull request"
          pr=${{ github.event.number }}
        elif [ ${{ github.event_name }} == 'merge_group' ]
          pr=$(echo ${{ github.event.merge_group.head_ref }} | grep -Eo "queue/main/pr-[0-9]+" | cut -d '-' -f2)
          echo "Event type: merge queue"
        else
          # pr=$(echo ${{ github.event.ref }} | grep -Eo "pr-[0-9]+" | cut -d '-' -f2)
          echo "Event type: not pull request or merge queue"
        fi

        echo "Summary ---"
        echo -e "\tPR: ${pr}"
        echo "pr=${pr}" >> $GITHUB_OUTPUT
