name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  # Nothing!

  ### Usually a bad idea / not recommended
  token:
    description: Specify token (GH or PAT), instead of inheriting one from the calling workflow
    default: ${{ github.token }}

outputs:
  pr:
    description: 'Associated pull request number'
    value: ${{ steps.vars.outputs.pr }}

runs:
  using: composite
  steps:
    # Process variables and inputs
    - uses: actions/checkout@v4
    - id: vars
      shell: bash
      run: |
        # Get PR number (different process for merge queue)
        if [ ${{ github.event_name }} == 'pull_request' ]
        then
          tag=${{ github.event.number }}
        else
          tag=$(echo ${{ github.event.merge_group.head_ref }} | grep -Eo "queue/main/pr-[0-9]+" | cut -d '-' -f2)
        fi

        echo "Summary ---"
        echo -e "\tTag (PR no): ${tag}"
        echo "tag=${tag}" >> $GITHUB_OUTPUT
