name: Manual Dispatch Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-action:
    name: Run action on manual dispatch
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Get PR number
        id: pr_resolver
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Output
        run: |
          echo "PR Number is: ${{ steps.pr_resolver.outputs.pr }}"
